spring:
  datasource:
    url: jdbc:mysql://localhost:3306/e_commerce_b
    username: root
    password: 101200Phuc
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update

stripe:
  secret-key: ""